name: Changelog
on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: mszostok/codeowners-validator@v0.6.0
        with:
          checks: "files,owners,duppatterns"
          experimental_checks: "notowned"
          # GitHub access token is required only if the `owners` check is enabled
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"